feat: add grouped manifest pr title pattern option (closes #1072)
googleapis/release-please pull request #1184
Opened 2021-12-31 12:00 UTC by axieum

This adds a new `group-pull-request-title-pattern` option to the manifest config to adjust the pull-request title when multiple packages are grouped/merged together into one manifest release pr.

- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code! That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Closes #1072 🦕

2021-12-31 12:00 UTC, axieum commented on docs/manifest-releaser.md
> +  "separate-pull-requests": false,
Add this option as it was missing.

2021-12-31 12:02 UTC, axieum commented on docs/manifest-releaser.md
> +  // grouped together in the one pull request.
```suggestion
  // grouped together in the one pull request.
  // this option has no effect when `separate-pull-requests` is `true`.
```

2021-12-31 12:17 UTC, axieum commented on src/manifest.ts
> +  groupPullRequestTitlePattern?: string;
I decided against naming it `mergedPullRequestTitlePattern` due to the keyword `merge` being ambiguous in this context

2021-12-31 12:27 UTC, axieum commented on src/manifest.ts
> +      manifestOptions?.groupPullRequestTitlePattern;
I did not update jsdoc for this constructor as it already appears out-of-date.

2021-12-31 12:27 UTC, axieum commented on src/manifest.ts
> +          this.groupPullRequestTitlePattern
I think passing the `manifestOptions` to all plugins would be cleaner, but in this `Manifest` constructor we don't capture the `manifestOptions` arg on this instance.

2021-12-31 12:27 UTC, axieum commented on src/strategies/base.ts
> +    logger.debug('pull request title pattern:', this.pullRequestTitlePattern);
I believe this was set to `warn` by mistake

2021-12-31 12:27 UTC, axieum commented on test/manifest.ts
> +    it('should allow customizing pull request title', async () => {
Perhaps this test could be simplified a bit, it looks a bit too long 🤔

2021-12-31 12:27 UTC, axieum commented on src/plugins/merge.ts
> +        rootRelease = candidate;
Since we're already iterating over each candidate pr, if we find the root package, we'll remember it for later when we build the pr title

2021-12-31 12:27 UTC, axieum commented on src/plugins/merge.ts
> +        rootRelease?.pullRequest.title.version,
If we found a root package release pr, we'll "hoist" its component and version args to this title pattern

2021-12-31 12:27 UTC, axieum commented on src/manifest.ts
> +  groupPullRequestTitlePattern?: string;
Open to suggestions, e.g. `pull-request-group-title-pattern`, etc.

2022-01-04 16:00 UTC, kalosisz commented
how is the `pullRequestTitlePattern` set if the manifest is created using `Manifest.fromManifest` (ie from manifest config file)?

2022-01-05 09:50 UTC, axieum commented
> how is the `pullRequestTitlePattern` set if the manifest is created using `Manifest.fromManifest` (ie from manifest config file)?

Thanks, should be fixed in 6aae04ec769508bef240af99d6e1709c9fc9146d

2022-01-05 09:52 UTC, axieum commented on src/manifest.ts
> +      defaultConfig.pullRequestTitlePattern,
This should fix the default pr title pattern not copying to each package

2022-01-10 23:57 UTC, chingor13 requested changes
Thanks! This is looking very good.

One question: what happens when there is no root component to hoist? Can we add a test case for this scenario?

2022-01-11 12:51 UTC, axieum commented
> Thanks! This is looking very good.
> 
> One question: what happens when there is no root component to hoist? Can we add a test case for this scenario?

@chingor13 I've added commit d872f56be7fd3a0f2025c8b9728f62a04bd5fdb3 which adds a test case, but unsure of how it should behave. Right now it just replaces them with blank.

2022-01-13 20:41 UTC, chingor13 approved these changes

2022-01-18 18:58 UTC, merged