feat: guess python package name by replacing dash to underscore
googleapis/release-please pull request #1230
Opened 2022-01-18 12:02 UTC by goatwu1993

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1229 🦕

2022-01-25 00:24 UTC, chingor13 requested changes
Thanks for this.

Can we add a test for this?

2022-01-25 00:24 UTC, chingor13 commented on src/strategies/python.ts
> +      const projectDirectoryName = projectName.replace('-', '_');
I wonder if something weird will happen if `projectDirectoryName` and `projectName` are the same. E.g. will the later API code be weird if there are 2 updates to the same file.

Another approach we could do is to use a `Set`, add both `projectName` and `projectDirectoryName`, then iterate over the members and add the 2 paths as a way to de-dup.

2022-02-04 21:11 UTC, bcoe commented
@goatwu1993 just a friendly nudge, looks like @chingor13 has a couple outstanding questions.

2022-03-11 12:55 UTC, goatwu1993 commented
I had updated with the set/iteration.

Test is lacking still. I checked the test and seems difficult to use sinom to stub a directory with name with dash replaced with underscore😖.

Any hint?

2022-04-28 04:51 UTC, closed without merging