feat: Adding support for manifest strategy paths to be files
googleapis/release-please pull request #1367
Opened 2022-04-11 00:53 UTC by TigerC10

2022-04-11 00:53 UTC, TigerC10 commented
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1366 🦕

2022-06-20 16:58 UTC, ScottGuymer commented
I have found a similar use case where I would like to version and release single files.

In this case it is for GitHub Reusable Workflows. I have a number of shared workflows that I keep in a repo but GitHub mandate that they must all live in the `.github/workflows` folder and cant be nested or moved from there.

2022-11-09 17:12 UTC, ScottGuymer commented
@chingor13 is this something that could move forward?

2022-11-14 11:49 UTC, ScottGuymer commented
@yoshi-nodejs can this be reviwed?

2022-12-11 21:05 UTC, npalm commented
@yoshi-nodejs would be great when the module can support file-based releases.

2023-01-05 05:55 UTC, TigerC10 commented
As my fork was fairly out of date, I've updated my fork to be in sync with the latest upstream.  No conflicts during update sync.

2023-01-05 16:17 UTC, chingor13 requested changes
This change of behavior will need tests to make sure it works (it currently will not work because the `fs` functions won't work on GitHub repo paths when there is no cloned version on the filesystem).

2023-01-05 16:17 UTC, chingor13 commented on src/manifest.ts
> +            existsSync(path) && lstatSync(path).isFile() ? dirname(path) : path,
There is no cloned git repo so these `fs` commands are all going to return `false` all the time.

2023-04-10 23:09 UTC, closed without merging