feat: implement python-poetry packages
googleapis/release-please pull request #1418
Opened 2022-05-06 16:51 UTC by goatwu1993

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Implement [packages](https://github.com/ChenJinGit/poetry/blob/50360f2dc96881398b428a08bd9288c4cc447d4e/docs/docs/pyproject.md#packages) of poetry pyproject.toml

Fixes #1229 🦕

2022-05-06 18:56 UTC, chingor13 requested changes
This is looking pretty good.

Question: these are just extra modules (that have an `__init__.py` file) that are all expected to be at the same version together? Would this prevent someone from using a manifest config that has multiple components at different versions?

2022-05-06 18:56 UTC, chingor13 commented on src/strategies/python.ts
> +        packagePaths.add((pkg.from || pkg.include).split('/')[0]);
Could the glob be something like `extra/path/**/*.py`? For example, perhaps there are 2 packages nested under `extra`.

2022-05-06 18:56 UTC, chingor13 commented on src/strategies/python.ts
> +      parsedPyProject?.tool?.poetry.packages.forEach(pkg => {
nit: the `?.` let's us chain these together. Then in the block, typescript knows that the fields exist so we can drop the `?.`.

```suggestion
      parsedPyProject?.tool?.poetry?.packages
    ) {
      parsedPyProject.tool.poetry.packages.forEach(pkg => {
```

2022-05-07 11:18 UTC, goatwu1993 commented
Hmm. I took a look and seems there is more to consider.

I will make some refactoring, maybe split some poetry toml logic and create a new PR

2022-05-07 11:18 UTC, closed without merging