feat(node-workspace): Allow to specify version prefix in config
googleapis/release-please pull request #1580
Opened 2022-08-16 20:28 UTC by danez

This allows a `versionPrefix` config option that can be set to a string (like `~`, `^`, ` `, `>=`) that will be used when updating linked local dependencies in a package.

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

2022-09-08 18:29 UTC, chingor13 requested changes
Thanks for this pull request and sorry for the delay in the review.

I'm torn on whether this option should be global (like it's implemented here) or should be localized to the `node-workspace` plugin (and potentially other workspace plugins). The reason being that these version prefixes only really apply to dependency declarations (which are handled by workspace plugins).

If localized to the `node-workspace` plugin, we would add a config like:

```json
{
  "plugins": [
    {
      "type": "node-workspace",
      "versionPrefix": "~"
    }
  ]
}
```

and then have the version prefix as a constructor argument to the workspace plugins.

What do you think?

2022-09-08 18:29 UTC, chingor13 commented on docs/manifest-releaser.md
> +  "version-prefix": true,
```suggestion
  "version-prefix": "^",
```

2022-09-08 18:30 UTC, chingor13 commented
Another option too, is to have the workspace plugins be smarter when updating the dependencies and preserve whatever prefix is currently being used.

2022-10-06 16:01 UTC, danez commented
> Another option too, is to have the workspace plugins be smarter when updating the dependencies and preserve whatever prefix is currently being used.

I actually like this the best, will try to find some time to look into this.

2022-10-26 11:26 UTC, closed without merging