chore: Adding new versioning strategies
googleapis/release-please pull request #1744
Opened 2022-11-08 14:30 UTC by ddixit14

This PR adds two new versioning strategies:

-  always-bump-minor : This VersioningStrategy always bumps the minor version
-  always-bump-major: This VersioningStrategy always bumps the major version

2022-11-08 15:12 UTC, ddixit14 commented
@chingor13 Need some insights to write new tests/make the tests pass. 

![image](https://user-images.githubusercontent.com/90280028/200601785-d1980846-f274-4fda-9c8f-d4c5e2a1e368.png)

2022-11-08 16:08 UTC, suztomo commented
For the new strategy, follow the test cases already written for "always-bump-patch". (I hope the tests are there)

2022-11-08 22:02 UTC, chingor13 commented
> Need some insights to write new tests/make the tests pass.

We use a snapshot of the `CLI --help` output to test the CLI help feature. Try running `npm run test:snap` which should rewrite the test snapshots.

2022-11-09 20:38 UTC, suztomo approved these changes

2022-11-09 20:39 UTC, suztomo commented
@ddixit14 Do you plan to add a test case in versioning-strategies/java.ts ?

2022-11-10 19:28 UTC, chingor13 requested changes
Yes, please add unit tests for the new versioning strategies even though they seem trivial.

Otherwise, LGTM.

2022-11-11 16:47 UTC, chingor13 approved these changes

2022-11-11 16:48 UTC, merged

2022-11-11 16:50 UTC, bcoe commented on test/versioning-strategies/always-bump-minor.ts
> +describe('MinorVersioningStrategy', () => {
Tiny nit, this should be `AlwaysBumpMinorStrategy`, my bad because I copy pasted this.