refactor: rename Salesforce to sfdx
googleapis/release-please pull request #1829
Opened 2023-01-26 08:26 UTC by scolladon

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1814 🦕

2023-01-27 17:09 UTC, scolladon commented
Hi @chingor13 !

I don't know why the tests are failing.
It does not seems to be related to my PR.

Should I do something on my end ?

2023-03-07 17:05 UTC, chingor13 requested changes
We can't really take this now, because it'd be a breaking change for users. It'd be possible to rename the class while keeping an alias for users' configuration that could specify `salesforce` or `sfdx` as the `release-type`.

2023-03-07 17:42 UTC, scolladon commented
> We can't really take this now, because it'd be a breaking change for users. It'd be possible to rename the class while keeping an alias for users' configuration that could specify `salesforce` or `sfdx` as the `release-type`.

I have added back the `salesforce` release-type mapper
But I have not added it back in the documentation
This way, previous user of the `salesforce` release type will be able to keep using it without breaking changes
And new comers will be able to use `sfdx` instead

2023-03-08 18:22 UTC, chingor13 requested changes
Thanks, almost there.

Also, is there an issue driving the need for this rename?

2023-03-08 18:22 UTC, chingor13 commented on __snapshots__/cli.js
> +    "php-yoshi", "python", "ruby", "ruby-yoshi", "rust", "sfdx", "simple",
Please leave both `salesforce` and `sfdx` as options for the CLI in case those are being used

2023-03-08 18:22 UTC, chingor13 commented on __snapshots__/cli.js
> +    "php-yoshi", "python", "ruby", "ruby-yoshi", "rust", "sfdx", "simple",
Please leave both `salesforce` and `sfdx` as options for the CLI in case those are being used

2023-03-08 21:55 UTC, scolladon commented
> Thanks, almost there.
> 
> Also, is there an issue driving the need for this rename?

I have not created a new issue, I reused the first one

2023-03-14 17:53 UTC, chingor13 approved these changes

2023-03-14 17:57 UTC, merged

2023-03-16 06:14 UTC, dschach commented
This is a good PR. Thank you, @scolladon