feat: add support for crystal lang projects
googleapis/release-please pull request #2036
Opened 2023-08-05 12:53 UTC by LucianBuzzo

This change adds support for projects written in
[Crystal](https://crystal-lang.org/). In a Crystal project, version information is stored in the `version` field of a file called `shard.yml` in the root of your project.
Functionally, this new crystal strategy is the same as the pre-existing Helm strategy, so I've used that as the basis for my implementation.

2023-08-05 12:55 UTC, LucianBuzzo commented
I've now signed the CLA, so the check should pass if re-run.

2023-08-10 12:46 UTC, LucianBuzzo commented
@chingor13 What do you think of this?

2023-09-01 08:02 UTC, LucianBuzzo commented
@bcoe I think you're a regular maintainer here, could you take a look at this PR when you have a moment? Thanks! 🙏

2023-09-05 16:03 UTC, chingor13 requested changes
Apologies I was OOO for several weeks.

Thank you for this and it's looking like a good start. We'll want some unit tests to make sure we don't have regressions (Perhaps look at the Helm strategy and chart.yaml updater tests).

Additionally, in order to use the strategies, it must be registered in the factory.ts so it can be loaded at configuration time.

2023-11-06 21:12 UTC, chingor13 commented
If you have time to add tests, the please reopen this PR.

2023-11-06 21:12 UTC, closed without merging