feat: prerelease type
googleapis/release-please pull request #2083
Opened 2023-09-19 17:11 UTC by kalosisz

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #2082 🦕 by introducing an argument to the `prerelease` versioning strategy.

It also deals with bumping versions with prerelease, but not having a number in the prerelease part in the following ways  
- `2.0.0-beta` will get bumped to `2.0.0-beta.1` if there are breaking changes or less
- `1.2.0-beta` will get bumped to `1.2.0-beta.1` if there are featurer or less
- `1.2.2-beta` will get bumped to `1.2.2-beta.1` if there are only patches.

The current behaviour of prelrease, ie. bumping `1.1.1-beta01` to `1.1.1-beta02` is preserved.

2023-09-26 18:37 UTC, chingor13 requested changes
Thanks for this. A few minor comments/nits.

2023-09-26 18:37 UTC, chingor13 commented on docs/manifest-releaser.md
> +  "prerelease-type": true,
Should this be a string?

2023-09-26 18:37 UTC, chingor13 commented on schemas/config.json
> +          "type": "boolean"
Same here - should this be a string?

2023-09-26 18:37 UTC, chingor13 commented on test/factory.ts
> +    it('should build with prerelease type', async () => {
nit: can we add this as a separate test and leave the existing one?

2023-10-16 15:27 UTC, kalosisz commented on docs/manifest-releaser.md
> +  "prerelease-type": true,
done

2023-10-25 07:02 UTC, kalosisz commented
hey @chingor13, please check the changes :) thanks

2023-10-26 22:22 UTC, chingor13 approved these changes
Thanks!

2023-10-26 22:23 UTC, merged