fix: versioning-strategy field incorrect
googleapis/release-please pull request #2450
Opened 2024-12-10 22:28 UTC by reggi

👋 hi (one of a couple different incoming prs) this is an easy one:

https://github.com/googleapis/release-please/blob/main/src/bin/release-please.ts#L304

The field is "versioning-strategy" not "versioning.

2025-01-24 17:26 UTC, reggi commented
Ping, curious if we can get this fixed / get an update on this?

2025-02-20 22:36 UTC, chingor13 requested changes

2025-02-20 22:36 UTC, chingor13 commented on schemas/config.json
> +        "versioning-strategy": {
`versioning` is the correct field in the config. The command line argument is `versioning-strategy` which is irrelevant to this schema.

2025-02-20 22:36 UTC, chingor13 commented on schemas/config.json
> +    "prerelease-type": true,
This one looks ok to add

2026-05-26 21:41 UTC, closed without merging