feat:  This adds the ability to pass an array of change log section options to the node releaser
googleapis/release-please pull request #538
Opened 2020-09-03 20:59 UTC by lholmquist

Fixes #537

2020-09-03 21:00 UTC, lholmquist commented
@googlebot I signed it!

2020-09-03 22:11 UTC, bcoe requested changes
Mind adding this for the main languages we advertise in the action:

`simple`, `terraform-module`, `ruby`,  `python`, `node`?

I would just double check that none of them override the value already,  if they do we can just make the override the default.

Thank you for the  contribution 👏

2020-09-05 18:33 UTC, bcoe approved these changes

2020-09-05 18:34 UTC, bcoe commented
@lholmquist thank you for the contributions 👌

2020-09-05 18:34 UTC, merged