fix: adjust patch rule for Java LTS strategy
googleapis/release-please pull request #857
Opened 2021-04-13 14:53 UTC by chingor13

The LTS branch will not bump the minor version - it will preserve the
major/minor/patch of the version it was patched from.

2021-04-15 23:40 UTC, bcoe commented on src/releasers/java/version.ts
>            if (!this.snapshot) {
mind adding a couple comments to `snapshot` vs., `lts-snapshot` explaining the nuances between how we bump the two types of releases?

2021-04-15 23:40 UTC, bcoe requested changes
I think it would be good to explain the nuance that requires the new `lts-snapshot`.

2021-04-16 00:09 UTC, chingor13 commented
> I think it would be good to explain the nuance that requires the new `lts-snapshot`.

Added a note in the docs/java-release.md and in the java-lts releaser

2021-04-19 20:49 UTC, bcoe approved these changes

2021-04-19 20:55 UTC, merged