docs: Add more detail around release process
googleapis/release-please pull request #872
Opened 2021-04-22 21:03 UTC by nzakas

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #778 🦕

I tried updating the README with the answers from #778. I hope this helps. Thanks so much for release-please!

2021-04-23 00:31 UTC, nzakas commented
@googlebot I signed it!

2021-04-23 17:06 UTC, chingor13 reviewed
Thanks for this!

2021-04-23 17:06 UTC, chingor13 commented on README.md
> +- `autorelease:published` means that a GitHub release has been published based on the Release PR
Let's remove this last label entry -- the actual publishing of packages is outside the scope of release-please and this is a convention other tools our team uses. Alternatively, we might mention that this is a suggestion for your choice of publishing automation to adopt.

2021-04-23 17:13 UTC, chingor13 approved these changes

2021-04-23 17:13 UTC, chingor13 commented on README.md
> +- `autorelease:published` means that a GitHub release has been published based on the Release PR
Eh, this is a nit, and we can fix this on our side.

2021-04-23 18:08 UTC, bcoe requested changes
Thanks for the contribution 👏 

Added a couple suggestions, let me know what you think.

2021-04-23 18:08 UTC, bcoe commented on README.md
> +- `autorelease:published` means that a GitHub release has been published based on the Release PR
```suggestion
- `autorelease:published` means that a GitHub release has been published based on the Release PR (_release-please does not automatically add this tag, but we recommend it as a convention for publication tooling_).
```

2021-04-23 18:08 UTC, bcoe commented on README.md
> +1. Updates your changelog file (for example `CHANGELOG.md`)
```suggestion
1. Updates your changelog file (for example `CHANGELOG.md`), along with other language specific files (for example `package.json`).
```

2021-04-24 00:20 UTC, nzakas commented
LGTM. Thanks!

2021-04-25 00:59 UTC, bcoe approved these changes

2021-04-25 01:15 UTC, merged

2021-04-25 01:15 UTC, bcoe commented
@nzakas thank you for the contribution 👍